### ISSUE TITLE
Version 2.0.0 fails to run

### ISSUE THREAD

**Issue by martincostello** [foo-software/lighthouse-check-status-action#32]
Dependabot updated my repos using this action from 1.0.1 to 2.0.0 overnight, and all the lighthouse usage is failing with a file not found error related to Python 3:

https://github.com/martincostello/adventofcode/actions/runs/3529380139/jobs/5920381943#step:1:28

**Comment by adamhenson** [comment]
Hello, while this is odd, I can't tell what the source of the issue is. We only updated our GitHub runner which [works fine in our repo](https://github.com/foo-software/lighthouse-check-status-action/actions/runs/3528093405/jobs/5917821590).

I looked at your CI files, and I don't understand why this is happening either. The only unknown part for me is how GitHub manages these runners and perhaps there is a bug in that mechanism (perhaps a bad cached image). I would give it another couple shots and if it doesn't work, I would recommend pinning version 1 of this GitHub Action (version 2 only bumped our GitHub Runner to Node.js 16 from 12).

**Comment by martincostello** [comment]
Looking at your commit history, maybe something to do with the changes to add node_modules?

The updates were all in PRs that failed, so I’ve just closed them and Dependabot will ignore until there’s another new release.

I can try manually updating another one again later in case it was an ephemeral issue and bad timing, but it consistently failed across 6 different repos.

**Comment by martincostello** [comment]
By coincidence another one was just opened. Again, still broken:

https://github.com/martincostello/costellobot/actions/runs/3530257900/jobs/5922071822#step:1:28

**Comment by dragonbear-os** [comment]
This is also broken for me, same error

**Comment by adamhenson** [comment]
I'm actually seeing [this error now](https://github.com/foo-software/lighthouse-check-status-action/actions/runs/3532699602/jobs/5927378449). I have no idea what is going on as it was simply a change to the Node.js version. And it seems that we're seeing two different errors.

```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './lib/websocket'
Require stack:
- /home/runner/work/lighthouse-check-status-action/lighthouse-check-status-action/node_modules/ws/index.js
- /home/runner/work/lighthouse-check-status-action/lighthouse-check-status-action/node_modules/lighthouse/lighthouse-core/gather/connections/cri.js
- /home/runner/work/lighthouse-check-status-action/lighthouse-check-status-action/node_modules/lighthouse/lighthouse-core/index.js
- /home/runner/work/lighthouse-check-status-action/lighthouse-check-status-action/node_modules/@foo-software/lighthouse-persist/dist/lighthousePersist.js
- /home/runner/work/lighthouse-check-status-action/lighthouse-check-status-action/node_modules/@foo-software/lighthouse-persist/dist/index.js
- /home/runner/work/lighthouse-check-status-action/lighthouse-check-status-action/node_modules/@foo-software/lighthouse-check/dist/localLighthouse.js
```

**Comment by adamhenson** [comment]
@dragonbear-os and @martincostello - I went ahead and added `ws`, even though this project doesn't use it directly, and it did fix my issue. I also upgraded all dependencies, so maybe that could help with the issues you saw.

I published a [new release (2.0.1)](https://github.com/foo-software/lighthouse-check-status-action/releases/tag/v2.0.1). Feel free to give it a try and let me know how it goes. If it errors, please provide the full error and / or link.

It runs and passes for me now, based on the last 2 workflows:
- https://github.com/foo-software/lighthouse-check-status-action/actions/runs/3533119549/jobs/5928335511
- https://github.com/foo-software/lighthouse-check-status-action/actions/runs/3533111082/jobs/5928315495

**Comment by martincostello** [comment]
Working with 2.0.1 👍: https://github.com/martincostello/costellobot/actions/runs/3533165448/jobs/5928441644

**Comment by adamhenson** [comment]
Phew, that was a weird one... thanks for confirming @martincostello

**Comment by dragonbear-os** [comment]
Confirmed that v2.0.1 also works for me

**Comment by adamhenson** [comment]
Thanks @dragonbear-os 🙏
