### ISSUE TITLE
Add major version label for each release

### ISSUE THREAD

**Issue by Tobi-mmt** [foo-software/lighthouse-check-status-action#35]
**Is your feature request related to a problem? Please describe.**
I want to define the version of the GH action to avoid a major version bump without my interaction. But I also don't want to update the minor and bugfix version manually. They can update autmatically. For that I want to define the GH action in my code like that, just defining the major version:

```yml
 - uses: foo-software/lighthouse-check-status-action@v2
 ```

Currently this leads to an error because the `v2` tag is not given at all. There are just version tags with the full version like `v2.0.1`.

**Describe the solution you'd like**
For each new release we have to define the detailed version tag and also update the major version tag for this release. Other actions do that curreently, like: https://github.com/actions/setup-node/tags . 
For example we could use the following GH action which manages the version tags automatically: [actions/publish-action](https://github.com/actions/publish-action)

**Describe alternatives you've considered**
Nothing in mind.

**Additional context**
nope

**Comment by adamhenson** [comment]
I disagree with the proposal here. Open source authors should not need to distribute an updated major version for every patch or minor version release. The package manager should handle this. For example, Docker and NPM handle this out of the box. The 2 packages you referenced are authored by GitHub, hence they are working around their own limitation.

Sorry, but I will not be doing this to makeup for GitHub's dysfunction. Please open an issue with GitHub Actions.

**Comment by adamhenson** [comment]
Related https://github.com/community/community/discussions/39519#discussioncomment-4185261

**Comment by Tobi-mmt** [comment]
I agree that the package manager should be able to get the current version if I say I want the version 2. 
But since the Github runner can not do that and Github decided to use a different approach - to let the maintiner move the tags - it is in your hands to change this behavior until github will change something/ or not.

So the docs of github says we have to move around the tags for new releases https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-tags-for-release-management. I guess this is then not a bug but an active decision of github. And yes it is not the best design decision they did, but it is as it is.

If you are on my site and you also think the enduser which implements your package should be able to select the major version, than we have to move the tags, maybe with an action which helps us here so we don't have to do it manually.
The other option is you don't agree with me. Thats also fine. Then we do nothing and I have to adjust the version of your package every now and then or hope "renovate" will do.

But blaming github at this point will not solve the problem in the near future in my opinion.

**Comment by adamhenson** [comment]
It's not that I don't agree with you, but it is true that I blame GitHub for this bad practice and non-standard way of distributing software. I think by silently working around the problem, we empower these large entities like GitHub and allow them to continue. I will not support this. This isn't the first bad practice GitHub Actions have enforced. It also enforces the versioning of `node_modules` and despite numerous reports of why this is bad, they haven't done anything about it. Not only would working around this bad practice encourage more of it and not stop it... it also would require overhead and failure points that could lead to obscure issues.
