### ISSUE TITLE
Update to Node.js v20

### ISSUE THREAD

**Issue by martincostello** [foo-software/lighthouse-check-status-action#36]
The action currently targets Node.js 16:

https://github.com/foo-software/lighthouse-check-status-action/blob/a7720bbbb04f70a3e4ec339237f8125e7eb4eb9a/action.yml#L20

This produces warnings from workflow runs using the action:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: foo-software/lighthouse-check-status-action@f22f8cdcaf593a986749d39fe21382526de3f501. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by adamhenson** [comment]
@martincostello thank you and updated. You can now use foo-software/lighthouse-check-status-action@v3.0.0 or foo-software/lighthouse-check-status-action@latest

**Comment by martincostello** [comment]
@adamhenson The v3.0.0 tag doesn't appear to work:

```
Download action repository 'foo-software/lighthouse-check-status-action@909aae2f54c7265094a4829989b69497165cc680' (SHA:909aae2f54c7265094a4829989b69497165cc680)
Error: Could not find file '/home/runner/work/_actions/_temp_ae9780c3-232b-45b8-8abb-59def2edaac1/_staging/foo-software-lighthouse-check-status-action-909aae2/node_modules/normalize-package-data/node_modules/.bin/semver'.
```

I guess it should be pointing at https://github.com/foo-software/lighthouse-check-status-action/commit/6695c892e0d7014d98caa0bb7539bd614b0918c3 instead of https://github.com/foo-software/lighthouse-check-status-action/commit/909aae2f54c7265094a4829989b69497165cc680 ?

**Comment by adamhenson** [comment]
Ughh... sorry @martincostello. GitHub Actions require that `node_modules` be committed and I neglected to do `git add .`

This should work now (as [tests are passing this time](https://github.com/foo-software/lighthouse-check-status-action/actions/runs/8970563937/job/24634375593)).

Can you try `foo-software/lighthouse-check-status-action@v3.0.1` or `foo-software/lighthouse-check-status-action@latest`?

**Comment by martincostello** [comment]
Yep, 3.0.1 works fine 👍

**Comment by adamhenson** [comment]
Thanks for confirming
